
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST'
export const PLAYER_SEND_COMMAND = 'PLAYER_SEND_COMMAND'
export const PLAYER_SET_CURRENT_TRACK = 'PLAYER_SET_CURRENT_TRACK'
export const PLAYER_PLAY = 'PLAYER_PLAY'
export const PLAYER_PAUSE = 'PLAYER_PAUSE'

export const SWITCH_LIGHT = 'SWITCH_LIGHT'
export const SET_WINDOW = 'SET_WINDOW'

export const TOGGLE_ALARM = 'TOGGLE_ALARM'
export const GET_ALARM_STATUS = 'GET_ALARM_STATUS'

export const VACUUM_SEND_COMMAND = 'VACUUM_CLEAN'

export const FETCH_LOGS_START = 'FETCH_LOGS_START'
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS'
export const FETCH_LOGS_ERROR = 'FETCH_LOGS_ERROR'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'



